services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: java-spring-mg
    container_name: java-spring-mg
    ports:
      - "7575:7575"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret


  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: 'rabbitFerid'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - '5672'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
volumes:
  postgres_data: